import type { Metadata } from "next";
import { Caveat, IBM_Plex_Mono } from "next/font/google";
import "@/styles/globals.css";
import Navigation from "@/components/Navigation";
import { Provider } from "react-redux";
import { store } from "@/DataMgr/store";

const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plexMono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${caveat.variable} ${plexMono.variable} flex flex-col h-screen font-plexMono antialiased text-white`}
      >
        <Provider store={store}>
          <Navigation />
          <div className="self-center h-1 w-[80%] bg-yellow mb-8" />
          {children}
          <div className="self-center h-1 w-[80%] bg-yellow mb-12" />
        </Provider>
      </body>
    </html>
  );
}
