import type { Metadata } from "next";
import { Caveat, IBM_Plex_Mono } from "next/font/google";
import "@/styles/globals.css";
import Navigation from "@/components/Navigation";

const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plexMono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${caveat.variable} ${plexMono.variable} font-plexMono antialiased text-white`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
